# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

id_last_digit = input("請輸入您身分證字號的尾數：")
id_last_digit= int(id_last_digit)
if id_last_digit % 2 ==1 :
    print("星期一三五日領")
else:
    print("星期二四六日領")