# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

user_int = input("請輸入一個正整數：")
user_int = int(user_int)
if user_int % 2 == 0 :
    print("{}是偶數".format(user_int))
else:
    print("{}是奇數".format(user_int))