# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

random_integers = [random.randint(1, 100) for i in range(10)]
is_odd_ints = []
for i in random_integers:
  if i % 2 == 1:
    is_odd_ints.append(True)
  else:
    is_odd_ints.append(False)
print(random_integers)
print(is_odd_ints)