# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

avengers_ratings = [8.1, 7.3, 8.5, 8.8] 
recommendations = [i for i in avengers_ratings if i >= 8] 
print(recommendations)