# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

years = [2012, 2015, 2018, 2019]
for year, movie in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))