# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

user_int = int(input("請輸入一個正整數："))
divisors = [] # 因數分解
for i in range(1, user_int+1):
  if user_int % 1 == 0:
    divisors.append(i)
print(divisors)
n_divisors = len(divisors)
if n_divisors == 2 :
  print("{}是質數".format(user_int))
else:
  print("{}不是質數".format(user_int))