# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

odds_squared = []
for i in range(10):
  if i % 2 == 1:
    odds_squared.append(i**2)
print(odds_squared)