# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

x = int(input("請輸入起始的正整數：")) 
y = int(input("請輸入終止的正整數："))
for i in range(x, y+1):
  print(i)