# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

x = 0.25
print(type(x))
print(x.as_integer_ratio())
print(type(x.as_integer_ratio()))