# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

def where_are_you_from(city, country):
    return city, country

print(where_are_you_from("Taipei", "Taiwan"))
print(type(where_are_you_from("Taipei", "Taiwan")))