# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

my_city, my_country = where_are_you_from("Taipei", "Taiwan")
print(my_city)
print(my_country)