# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

primes_list = [2, 3, 5, 7, 11]
primes_list[-1] = 13 # update
print(primes_list)