# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

city = input("請輸入您所在的城市：")
weather = input("請輸入現在的天氣：")
print("我在{}，天氣{}".format(city, weather))