# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

test_str = 'azcbobobegghakl'
n_char = len(test_str)
print(n_char)
for i in range(12):
  print(test_str[i:i+3])