# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

n_vowels = 0
for i in 'azcbobobegghakl':
  if i in ['a','e','i','o','u']:
    print(i)
    n_vowels +=1
print(n_vowels)