# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

print(weekdays[-1])
print(weekdays[-2])
print(weekdays[-3])
print(weekdays[-4])
print(weekdays[-5])