# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

lucky_num_0 = 7
lucky_num_1 = 24
lucky_num_2 = 5566
lucky_numbers = [7, 24, 5566]