# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2Z12c316vgm4zPrzVbeQDTd9H97el_L
"""

print("Hello World")