# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

shaq_weight = 147
shaq_height = 216
shaq_bmi = shaq_weight/(shaq_height/100)**2
print(shaq_bmi)