# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

name = input("請輸入姓名: ")
shaq_height = eval(input("請輸入身高: "))
shaq_weight = eval(input("請輸入體重: "))
shaq_bmi = shaq_weight/(shaq_height/100)**2
print("{}的身體質量指數為：{:.2f}".format(name,shaq_bmi)) 
print("{}是否過重：{}".format(name,shaq_bmi > 30))