# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

movie_time = 181
movie_rating = 8.5
movie_title = "Avengers: Endgame"

print(movie_time) 
print(movie_rating) 
print(movie_title)

print(type(movie_time)) 
print(type(movie_rating)) 
print(type(movie_title))