# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

counter = 0
while i <= 10:
    if i % 2 == 0:
        counter += 1
    i += 1
print(counter)