# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Zf9FALuFGoo31qbOvUDqhRIEi_petyq
"""

player_height = float(input("請輸入球員身高(公尺):"))
player_weight = float(input("請輸入球員體重(公斤):"))
player_bmi = player_weight / player_height**2
bmi_label = None
if player_bmi > 30:
    bmi_label = 'Obese'
if player_bmi <= 30 and player_bmi > 25:
    bmi_label = 'Overweight'
if player_bmi <= 25 and player_bmi > 18.5:
    bmi_label = 'Normal weight'
if player_bmi <= 18.5:
    bmi_label = 'Underweight'
print(player_bmi)
print(bmi_label)